services:
  - type: web
    name: number-werewolf
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm run render-build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
